steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/virtuoso
      tags: ${CI_COMMIT_SOURCE_BRANCH/\//-}
      platforms: linux/amd64,linux/arm64
      purge: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  event:
    - pull_request
  branch: [feature/*]
