steps:
  build-and-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/virtuoso
      tags: ${CI_COMMIT_TAG##v} # strips v from the tag
      platforms: linux/amd64,linux/arm64
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  - event: tag
    ref: refs/tags/v*
